# Site settings
title: Let's make robots!
description: "A website resource for Maker Lab's robotics course, held in July 2015 for the Dharma School in Brighton, UK"
url: "http://letsmake-uk.github.io/dharma-school"
author:
  name: "N. Seymour-Smith and L. d'Aboville"
  url: "http://letsmake.io"

# Build settings
baseurl: /dharma-school/
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
makerlab: "http://makerclub.org/makerlab"